### PR TITLE
Fix multiple clicks on confirm or cancel button (#34)

### LINKED ISSUE #34: two times click "confirm" button cause an error
When I click confirm button two times, very fast, I get an error for the second click.

```
TypeError: resolve is not a function
(anonymous function)
node_modules/material-ui-confirm/dist/material-ui-confirm.esm.js:219
```

```
handleClose();
  217 | }, [reject, handleClose]);
  218 | var handleConfirm = useCallback(function () {
> 219 |   resolve();
      | ^  220 |   handleClose();
  221 | }, [resolve, handleClose]);
```

Is there a way to disable Confirm button after first click?

### PR DESCRIPTION
**Pull request by ypahalajani**
Fixes #34

Hi @jonatanklosko 

The issue was caused because the current code is maintaining related state variables in different hook variables. This is not a recommended approach because it can cause incorrect/unreliable state updates like in this case.

So, I did not re-wire the logic (I did not merge all the states into a single react state variable) but instead introduced a (new) `state` variable (literally, the state of Dialog component - `idle`, `open`, `submitting`).

This helps in catching the incorrect flows and we can now correctly map the `open` state of the MUI Dialog component now.

### CODE REVIEW

File: src/ConfirmProvider.js [hunk 1]
```diff
@@ -40,36 +40,56 @@ const buildOptions = (defaultOptions, options) => {
...
-  }, [resolve, handleClose]);
+    if (state === 'open') {
+      resolve();
+      setState('submitting');
+    }
+  }, [resolve, state]);
+
+  useEffect(() => {
+    if (state === 'submitting') {
+      handleClose();
```
Comment (jonatanklosko) [inline src/ConfirmProvider.js:82]: `handleClose` is always executed after confirm/cancel, because we pass it as `onClose` to the dialog, so I think this would call it twice.

File: src/ConfirmProvider.js [hunk 2]
```diff
@@ -40,36 +40,56 @@ const buildOptions = (defaultOptions, options) => {
...
     setResolveReject([]);
+    setState('idle');
   }, []);
 
   const handleCancel = useCallback(() => {
-    reject();
-    handleClose();
-  }, [reject, handleClose]);
+    if (state === 'open') {
+      reject();
```
Comment (jonatanklosko) [inline src/ConfirmProvider.js:68]: I think we could just do `if (reject) {}` to achieve the same, without an additional state and effect. wdyt?

**Review by jonatanklosko — COMMENTED** [review]
Hey @ypahalajani, thanks for looking into this! Some comments from me :)

File: src/ConfirmProvider.js (hunk 2 above)
Comment (ypahalajani) [reply src/ConfirmProvider.js:68]: Yes, I agree that it would solve the issue.

But, the check on `state` variable's value as `open` indicates more clearly that the resolve and reject are already available, so I did not have to check it explicitly.

Also, if this was a typescript project, this line would definitely throw a TS error that reject could be `undefined` 😅

Comment (jonatanklosko) [reply src/ConfirmProvider.js:68]: Well, checking if we have `reject` is more a more direct way of ensuring it's callable, but I get your point. The advantage is that we wouldn't need the additional useEffect, which makes us re-render.

File: src/ConfirmProvider.js (hunk 1 above)
Comment (ypahalajani) [reply src/ConfirmProvider.js:82]: Correct, that is why I updated I moved "calling `handleClose`" inside the `useEffect` to make this "transactional".

**Transactions being:**
1. Click on confirm => call `handleConfirm` => set state to "submitting" => Inside `useEffect`, call `handleClose`
2. Click on cancel => call `handleCancel` => set state to "submitting" => Inside `useEffect`, call `handleClose`

If a user clicks the confirm button twice then, before the second click, the state is already in `submitting` state, so it won't submit the form again solving the issue at hand

Comment (jonatanklosko) [reply src/ConfirmProvider.js:82]: Yeah, my point is that we still pass `onClose={handleClose}` to the dialog, so it will be called by the dialog too, so currently it is:

1. Click on confirm => call `handleConfirm` => set state to "submitting" => call `handleClose` => Inside `useEffect`, call `handleClose`

File: src/ConfirmProvider.js (hunk 2 above)
Comment (ypahalajani) [reply src/ConfirmProvider.js:68]: Yep

File: src/ConfirmProvider.js (hunk 1 above)
Comment (ypahalajani) [reply src/ConfirmProvider.js:82]: > Click on confirm => call handleConfirm => set state to "submitting" => call handleClose => Inside useEffect, call handleClose

The updated code of `handleConfirm` in this PR, won't call `handleClose`.

In the new code, handleClose is called from two places only:
1. If someone clicked on close button => passed via `onClose` prop to the `ConfirmationDialog` component.
2. If in the `useEffect` hook it is detected the `state === 'submitting'`  (happens for confirm/cancel click)

Comment (ypahalajani) [reply src/ConfirmProvider.js:82]: `handleConfirm` will definitely will called twice but `handleClose` will be called once because the state had already be `submitting` when confirm button was click for the first time.

Comment (jonatanklosko) [reply src/ConfirmProvider.js:82]: Ah nevermind, for a moment I thought dialog `onClose` would also be called in confirm/cancel, but that's not the case and we explicitly call `handleClose` in those cases. So your reasoning makes perfect sense.

That said, I would still go with the reject/resolve check instead to avoid the additional useEffect and the intermediate submitting state :)

Comment (ypahalajani) [reply src/ConfirmProvider.js:82]: I agree that the reject/resolve check is the minimal way to fix it but it felt like bandaging the code so I did not go ahead in that direction.
But, you want me to fix it that way, I can certainly do that.

Comment (jonatanklosko) [reply src/ConfirmProvider.js:82]: It's surely subjective, but keeping less state feels like less complexity, so I'd appreciate the other solution yeah :)

Comment (ypahalajani) [reply src/ConfirmProvider.js:66]: Hey @jonatanklosko , I've pushed the updated code. Please review

**Review by jonatanklosko — APPROVED** [review]
@ypahalajani Thanks for the fix and discussion :)

**Comment by ypahalajani** [comment]
🆒  @jonatanklosko

**Comment by ypahalajani** [comment]
Also, could you please label this PR with **hacktoberfest-accepted** so that, it is counted in the hacktoberfest 2021?

**Comment by jonatanklosko** [comment]
Absolutely, done!
